# Generated by Django 5.1.6 on 2025-07-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
