# Generated by Django 5.1.6 on 2025-07-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_borrow_return_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='return_request',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='returned',
        ),
        migrations.AddField(
            model_name='borrow',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Request'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
