# Generated by Django 5.1.6 on 2025-07-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_borrow_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Request'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('returned', 'Returned')], default='Borrow', max_length=20),
        ),
    ]
